<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>BatchParamUpdate.UI.Wpf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BatchParamUpdate.Application\BatchParamUpdate.Application.csproj" />
    <ProjectReference Include="..\BatchParamUpdate.Domain\BatchParamUpdate.Domain.csproj" />
  </ItemGroup>
</Project>
