<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>BatchParamUpdate.Installer</RootNamespace>
    <AssemblyName>Installer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BatchParamUpdate.Domain\BatchParamUpdate.Domain.csproj" />
  </ItemGroup>
</Project>
